reorder to ensure boxbuilder user exists in chroot before it is used

diff --git a/boxbuilder_build_ami b/boxbuilder_build_ami
--- a/boxbuilder_build_ami
+++ b/boxbuilder_build_ami
@@ -263,38 +263,7 @@ create_chroot_jail_from_base_image() {
     # Sometimes this is needed even though image was resized before mount with uec-resize-image?
     sudo resize2fs /dev/loop4 5G
   fi
-
-  echo "$_log_prefix Performing initial setup on chroot jail at $_imagedir ..."
-  # Allow network access from chroot environment
-  sudo cp /etc/resolv.conf $_imagedir/etc/
-  # Remove hostname
-  sudo rm -f $_imagedir/etc/hostname
-  if [[ $_platform = 'debian' ]]; then
-    sudo /usr/sbin/chroot $_imagedir apt-key adv --keyserver keyserver.ubuntu.com --recv-keys BE09C571
-  fi
-  sudo /usr/sbin/chroot $_imagedir su - $boxbuilder_user -c "touch /home/$boxbuilder_user/.bash_history"
-  sudo /usr/sbin/chroot $_imagedir mount -t proc none /proc
-  sudo /usr/sbin/chroot $_imagedir mount -t devpts none /dev/pts
   echo "$_log_prefix Finished creating chroot jail from base image $_imagesource ..."
-}
-
-grant_nopasswd_sudo_access() {
-  echo "$_log_prefix  Checking no-password sudo access for 'admin' group in chroot jail ..."
-  if ! sudo /usr/sbin/chroot $_imagedir 'grep -e "%admin.*ALL.*=.*NOPASSWD.*:.*ALL" /etc/sudoers)'; then
-    echo "$_log_prefix  Giving user $boxbuilder_user NO PASSWORD sudo privileges"
-    sudo /usr/sbin/chroot $_imagedir rm -f /tmp/sudoers.new
-    sudo /usr/sbin/chroot $_imagedir cp /etc/sudoers /etc/sudoers.bak
-    sudo /usr/sbin/chroot $_imagedir cp /etc/sudoers /tmp/sudoers.new
-    _new_sudoers_line="%admin ALL=NOPASSWD: ALL"
-    sudo /usr/sbin/chroot $_imagedir sh -c "echo \"$_new_sudoers_line\" >> /tmp/sudoers.new"
-    if ! sudo /usr/sbin/chroot $_imagedir visudo -c -s -f /tmp/sudoers.new; then
-      echo "$_log_prefix  error on line $LINENO -: Syntax error in /tmp/sudoers.new in chroot jail.  Please manually add this entry using visudo: $_new_sudoers_line"
-      return 1
-    fi
-    sudo /usr/sbin/chroot $_imagedir cp /tmp/sudoers.new /etc/sudoers
-  else
-    echo "$_log_prefix  admin group already appears to have NOPASSWD sudo access."
-  fi
 }
 
 ensure_boxbuilder_user_exists() {
@@ -323,7 +292,39 @@ automatically created..."
     echo "$_log_prefix  boxbuilder_user '$boxbuilder_user' was NOT successfully created in chroot jail - something went wrong :( - try setting boxbuilder_debug=true ..."
     return 1
   fi
-  grant_nopasswd_sudo_access
+}
+
+grant_nopasswd_sudo_access_in_chroot() {
+  echo "$_log_prefix  Checking no-password sudo access for 'admin' group in chroot jail ..."
+  if ! sudo /usr/sbin/chroot $_imagedir 'grep -e "%admin.*ALL.*=.*NOPASSWD.*:.*ALL" /etc/sudoers)'; then
+    echo "$_log_prefix  Giving user $boxbuilder_user NO PASSWORD sudo privileges"
+    sudo /usr/sbin/chroot $_imagedir rm -f /tmp/sudoers.new
+    sudo /usr/sbin/chroot $_imagedir cp /etc/sudoers /etc/sudoers.bak
+    sudo /usr/sbin/chroot $_imagedir cp /etc/sudoers /tmp/sudoers.new
+    _new_sudoers_line="%admin ALL=NOPASSWD: ALL"
+    sudo /usr/sbin/chroot $_imagedir sh -c "echo \"$_new_sudoers_line\" >> /tmp/sudoers.new"
+    if ! sudo /usr/sbin/chroot $_imagedir visudo -c -s -f /tmp/sudoers.new; then
+      echo "$_log_prefix  error on line $LINENO -: Syntax error in /tmp/sudoers.new in chroot jail.  Please manually add this entry using visudo: $_new_sudoers_line"
+      return 1
+    fi
+    sudo /usr/sbin/chroot $_imagedir cp /tmp/sudoers.new /etc/sudoers
+  else
+    echo "$_log_prefix  admin group already appears to have NOPASSWD sudo access."
+  fi
+}
+
+perform_initial_chroot_jail_setup() {
+  echo "$_log_prefix Performing initial setup on chroot jail at $_imagedir ..."
+  # Allow network access from chroot environment
+  sudo cp /etc/resolv.conf $_imagedir/etc/
+  # Remove hostname
+  sudo rm -f $_imagedir/etc/hostname
+  if [[ $_platform = 'debian' ]]; then
+    sudo /usr/sbin/chroot $_imagedir apt-key adv --keyserver keyserver.ubuntu.com --recv-keys BE09C571
+  fi
+  sudo /usr/sbin/chroot $_imagedir su - $boxbuilder_user -c "touch /home/$boxbuilder_user/.bash_history"
+  sudo /usr/sbin/chroot $_imagedir mount -t proc none /proc
+  sudo /usr/sbin/chroot $_imagedir mount -t devpts none /dev/pts
 }
 
 run_boxbuilder_bootstrap_in_chroot_jail_to_build_image() {
@@ -443,8 +444,10 @@ run() {
   set_ec2_credentials
   install_packages
   set_up_ec2_tools
-  ensure_boxbuilder_user_exists
   create_chroot_jail_from_base_image
+  ensure_boxbuilder_user_exists
+  grant_nopasswd_sudo_access_in_chroot
+  perform_initial_chroot_jail_setup
   run_boxbuilder_bootstrap_in_chroot_jail_to_build_image
   copy_image_to_ami
   echo "$_log_prefix Finished and exiting successfully"
