make debugging flags consistent across all scripts, and turn up all the way

diff --git a/boxbuilder b/boxbuilder
--- a/boxbuilder
+++ b/boxbuilder
@@ -3,12 +3,21 @@
 #  http://github.com/thewoolleyman/boxbuilder
 #  Copyright (c) 2010 Chad Woolley - The MIT License
 
+export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
+
+set -o errexit
 set -o noclobber
-set -e
-set -o pipefail
 set -o nounset
-set -u
-trap 'echo BOXBUILDER - boxbuilder: error on line $LINENO' ERR
+set -o pipefail
+set –o verbose
+set -o xtrace
+
+handle_error() {
+  echo "BOXBUILDER - boxbuilder: error on line $LINENO"
+  exit 1 # TODO: return original error code.  how?
+}
+
+trap handle_error ERR EXIT INT TERM
 
 setup() {
   if [ -e $HOME/.boxbuilderrc ]; then
@@ -72,9 +81,9 @@ install_packages() {
     else
       _package_version=${_package#*=}
     fi
-    set +e
+    set +o errexit
     _package_status=$(dpkg -l $_package_name | grep "ii  $_package_name" | grep "$_package_version")
-    set -e
+    set -o errexit
     if [[ -z $_package_status ]]; then
       echo "BOXBUILDER - boxbuilder:  Package $_package is NOT already installed..."
       _packages_missing=true
@@ -136,23 +145,23 @@ enable_rvm() {
 
 install_rvm_ruby() {
   echo "BOXBUILDER - boxbuilder:  Installing RVM default ruby: $boxbuilder_default_ruby"
-  set +u
-  set +e
+  set +o nounset
+  set +o errexit
   if [[ -z $($HOME/.rvm/bin/rvm info | head -n 1 | grep $boxbuilder_default_ruby) ]] ; then
     $HOME/.rvm/bin/rvm install $boxbuilder_default_ruby
     echo "BOXBUILDER - boxbuilder:  Finished installing RVM default ruby: $boxbuilder_default_ruby"
   else
     echo "BOXBUILDER - boxbuilder:  Not installing RVM Ruby $boxbuilder_default_ruby because it is already installed ..."
   fi
-  set -u
-  set -e
+  set -o nounset
+  set -o errexit
 }
 
 set_rvm_default_ruby() {
   echo "BOXBUILDER - boxbuilder:  Setting RVM default ruby: $boxbuilder_default_ruby"
-  set +e
+  set +o errexit
   $HOME/.rvm/bin/rvm --default use $boxbuilder_default_ruby
-  set -e
+  set -o errexit
   echo "BOXBUILDER - boxbuilder:  Finished setting RVM default ruby: $boxbuilder_default_ruby"
 }
 
@@ -162,9 +171,9 @@ setup_rvm() {
   for init_file in $HOME/.bashrc $HOME/.bash_profile
   do
     if [[ -e $init_file ]] ; then
-      set +e  # turn off return code checking for now, failing with output 'tput: unknown terminal "unknown"'
+      set +o errexit  # turn off return code checking for now, failing with output 'tput: unknown terminal "unknown"'
       enable_rvm
-      set -e
+      set -o errexit
     fi
   done
   install_rvm_ruby
@@ -201,14 +210,14 @@ download_chef_repos() {
     else
       echo "BOXBUILDER - boxbuilder:  $_repo_path already exists, pulling and updating ..."
       echo $_repo_path
-      set +u
+      set +o nounset
       cd $_repo_path
-      set -u
+      set -o nounset
       git pull
       git submodule update --init
-      set +u
+      set +o nounset
       cd -
-      set -u
+      set -o nounset
     fi
   done
   echo "BOXBUILDER - boxbuilder:  Finished downloading/updating Chef Repos..."
diff --git a/boxbuilder_bootstrap b/boxbuilder_bootstrap
--- a/boxbuilder_bootstrap
+++ b/boxbuilder_bootstrap
@@ -3,13 +3,21 @@
 #  http://github.com/thewoolleyman/boxbuilder
 #  Copyright (c) 2010 Chad Woolley - The MIT License
 
-set -o noclobber
-set -e
+export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
+
 set -o errexit
-set -o pipefail
+set -o noclobber
 set -o nounset
-set -u
-trap 'echo BOXBUILDER - boxbuilder_bootstrap: error on line $LINENO' ERR EXIT INT TERM
+set -o pipefail
+set –o verbose
+set -o xtrace
+
+handle_error() {
+  echo "BOXBUILDER - boxbuilder_bootstrap: error on line $LINENO"
+  exit 1 # TODO: return original error code.  how?
+}
+
+trap handle_error ERR EXIT INT TERM
 
 setup() {
   echo "BOXBUILDER - boxbuilder_bootstrap:  Environment variable setup ..."
@@ -32,19 +40,19 @@ setup() {
 
 grant_nopasswd_sudo_access() {
   echo "BOXBUILDER: Checking 'admin' group membership for user $boxbuilder_user on host $boxbuilder_host."
-  set +e
+  set +o errexit
   groups | grep -q -e "admin"
   if [ ! $? = 0 ]; then
     echo "BOXBUILDER - boxbuilder_bootstrap: error on line $LINENO - user $boxbuilder_user is not a member of the 'admin' group on host $boxbuilder_host.  Please add..."
     return 1
   fi
-  set -e
+  set -o errexit
 
   echo "BOXBUILDER - boxbuilder_bootstrap: Checking no-password sudo access for 'admin' group on host $boxbuilder_host and adding if necessary.  If prompted, please type your password, or ctrl-c to abort..."
-  set +e
+  set +o errexit
   sudo grep -e "%admin.*ALL.*=.*NOPASSWD.*:.*ALL" /etc/sudoers
   if [ ! $? = 0 ]; then
-    set -e
+    set -o errexit
     echo "BOXBUILDER - boxbuilder_bootstrap: Giving user $boxbuilder_user NO PASSWORD sudo privileges"
     sudo rm -f /tmp/sudoers.new
     sudo cp /etc/sudoers /etc/sudoers.bak
@@ -55,16 +63,16 @@ grant_nopasswd_sudo_access() {
       echo "BOXBUILDER - boxbuilder_bootstrap: error on line $LINENO - Could not add create /tmp/sudoers.new on host $boxbuilder_host.  Please manually add this entry using visudo: $new_sudoers_line"
       return 1
     fi
-    set -e
+    set -o errexit
     sudo visudo -c -s -f /tmp/sudoers.new
-    set +e
+    set +o errexit
     if [ ! $? = 0 ]; then
       echo "BOXBUILDER - boxbuilder_bootstrap: error on line $LINENO -: Syntax error in /tmp/sudoers.new on host $boxbuilder_host.  Please manually add this entry using visudo: $new_sudoers_line"
       return 1
     fi
     sudo cp /tmp/sudoers.new /etc/sudoers
   else
-    set -e
+    set -o errexit
     echo "BOXBUILDER - boxbuilder_bootstrap: admin group already appears to have NOPASSWD sudo access."
   fi  
 }
diff --git a/boxbuilder_build_ami b/boxbuilder_build_ami
--- a/boxbuilder_build_ami
+++ b/boxbuilder_build_ami
@@ -3,13 +3,21 @@
 #  http://github.com/thewoolleyman/boxbuilder
 #  Copyright (c) 2010 Chad Woolley - The MIT License
 
-set -o noclobber
-set -e
+export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
+
 set -o errexit
-set -o pipefail
+set -o noclobber
 set -o nounset
-set -u
-trap 'echo BOXBUILDER - boxbuilder_build_ami: error on line $LINENO' ERR EXIT INT TERM
+set -o pipefail
+set –o verbose
+set -o xtrace
+
+handle_error() {
+  echo "BOXBUILDER - boxbuilder_build_ami: error on line $LINENO"
+  exit 1 # TODO: return original error code.  how?
+}
+
+trap handle_error ERR EXIT INT TERM
 
 setup() {
   echo "BOXBUILDER - boxbuilder_build_ami:  Environment variable setup ..."
@@ -164,10 +172,10 @@ copy_image_to_ami() {
 
   echo "BOXBUILDER - boxbuilder_build_ami: Ensuring no existing volume is already attached at /dev/sdi ..."
   # TODO: Why must -K and -C be passed?  Why can't it find exported vars in subshell?
-  # TODO: and why do we need set +e?
-  set +e
+  # TODO: and why do we need set +o errexit?
+  set +o errexit
   _existing_volumeid=$(ec2-describe-volumes -K $EC2_PRIVATE_KEY -C $EC2_CERT | grep -e '^ATTACHMENT.*/dev/sdi' | cut -f2)
-  set -e
+  set -o errexit
   if [[ ! -z $_existing_volumeid ]]; then
     echo "BOXBUILDER - boxbuilder_build_ami: Volume $_existing_volumeid is already attached at /dev/sdi.  Detaching and deleting ..."
     ec2-detach-volume -f $_existing_volumeid
diff --git a/boxbuilder_remote_bootstrap b/boxbuilder_remote_bootstrap
--- a/boxbuilder_remote_bootstrap
+++ b/boxbuilder_remote_bootstrap
@@ -3,13 +3,21 @@
 #  http://github.com/thewoolleyman/boxbuilder
 #  Copyright (c) 2010 Chad Woolley - The MIT License
 
-set -o noclobber
-set -e
+export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
+
 set -o errexit
-set -o pipefail
+set -o noclobber
 set -o nounset
-set -u
-trap 'echo BOXBUILDER - boxbuilder_remote_bootstrap: error on line $LINENO' ERR EXIT INT TERM
+set -o pipefail
+set –o verbose
+set -o xtrace
+
+handle_error() {
+  echo "BOXBUILDER - boxbuilder_remote_bootstrap: error on line $LINENO"
+  exit 1 # TODO: return original error code.  how?
+}
+
+trap handle_error ERR EXIT INT TERM
 
 exec_remotely() {
   local arg_array i rc
diff --git a/boxbuilder_remote_build_ami b/boxbuilder_remote_build_ami
--- a/boxbuilder_remote_build_ami
+++ b/boxbuilder_remote_build_ami
@@ -3,13 +3,21 @@
 #  http://github.com/thewoolleyman/boxbuilder
 #  Copyright (c) 2010 Chad Woolley - The MIT License
 
-set -o noclobber
-set -e
+export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
+
 set -o errexit
-set -o pipefail
+set -o noclobber
 set -o nounset
-set -u
-trap 'echo BOXBUILDER - boxbuilder_remote_build_ami: error on line $LINENO' ERR EXIT INT TERM
+set -o pipefail
+set –o verbose
+set -o xtrace
+
+handle_error() {
+  echo "BOXBUILDER - boxbuilder_remote_build_ami: error on line $LINENO"
+  exit 1 # TODO: return original error code.  how?
+}
+
+trap handle_error ERR EXIT INT TERM
 
 exec_remotely() {
   local arg_array i rc
@@ -123,9 +131,9 @@ set_up_ec2_tools() {
     # wget -O $_ec2_api_tools_zipfile $boxbuilder_ec2_api_tools_url # TODO: uncomment after debugging
     echo "BOXBUILDER - boxbuilder_remote_build_ami: Reading top-level directory for $_ec2_api_tools_zipfile ..."
     # Zipfile is structured with top-level directory containing the release date, so we must determine what it is, extract, and symlink it to _ec2_api_tools_path
-    set +e
+    set +o errexit
     _first_zipfile_listing_entry=$(unzip -l $_ec2_api_tools_zipfile | head -n4 | tail -n1) # _first_zipfile_listing_entry should be top-level zipfile dir
-    set -e
+    set -o errexit
     _top_level_zipfile_dir=${_first_zipfile_listing_entry##* } # grab just last space-delimited directory component from _first_zipfile_listing_entry
     _top_level_zipfile_dir=${_top_level_zipfile_dir%%/} # strip trailing slash
     echo "BOXBUILDER - boxbuilder_remote_build_ami: Unzipping $_ec2_api_tools_zipfile to $_ec2_tools_path ..."
diff --git a/test/boxbuilder_test b/test/boxbuilder_test
--- a/test/boxbuilder_test
+++ b/test/boxbuilder_test
@@ -3,11 +3,21 @@
 #  http://github.com/thewoolleyman/boxbuilder
 #  Copyright (c) 2010 Chad Woolley - The MIT License
 
+export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
+
+set -o errexit
 set -o noclobber
-set -e
-set -o pipefail
 set -o nounset
-trap 'echo BOXBUILDER: boxbuilder_test: error on line $LINENO' ERR
+set -o pipefail
+set –o verbose
+set -o xtrace
+
+handle_error() {
+  echo "BOXBUILDER - boxbuilder_test: error on line $LINENO"
+  exit 1 # TODO: return original error code.  how?
+}
+
+trap handle_error ERR EXIT INT TERM
 
 exec_remotely_quiet() {
   local arg_array i rc
diff --git a/test/test_helper b/test/test_helper
--- a/test/test_helper
+++ b/test/test_helper
@@ -1,11 +1,23 @@
+#!/usr/bin/env bash
+
 #  http://github.com/thewoolleyman/boxbuilder
 #  Copyright (c) 2010 Chad Woolley - The MIT License
 
+export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
+
+set -o errexit
 set -o noclobber
-set -e
-set -o pipefail
 set -o nounset
-trap 'echo BOXBUILDER: boxbuilder_test: error on line $LINENO' ERR
+set -o pipefail
+set –o verbose
+set -o xtrace
+
+handle_error() {
+  echo "BOXBUILDER - test_helper: error on line $LINENO"
+  exit 1 # TODO: return original error code.  how?
+}
+
+trap handle_error ERR EXIT INT TERM
 
 assert_equal() {
   set +o nounset
@@ -19,7 +31,7 @@ assert_equal() {
 }
 
 assert_match() {
-  set +e
+  set +o errexit
   set +o nounset
   echo $2 | grep -e $1
   if [[ ! $? = 0 ]]; then
@@ -29,5 +41,5 @@ assert_match() {
     return 1
   fi
   set -o nounset
-  set -e
+  set -o errexit
 }
